[build]
publish = "outreach/website"
command = """
    # Create necessary directories
    mkdir -p outreach/website/documents outreach/website/download

    # Copy documentation
    cp -f docs/Spielbeschreibungen/*.pdf outreach/website/documents/ || echo "Warning: PDF files not copied"

    # Build the JAR file
    ./gradlew jar || echo "Failed to build JAR, continuing deployment"

    # Copy the JAR file to the download directory
    cp -f build/libs/SettlersOfAsgard.jar outreach/website/download/ || echo "Warning: JAR file not found"
  """

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
conditions = {Role = ["admin"]}

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/download/*"
[headers.values]
Cache-Control = "public, max-age=86400"