[build]
publish = "outreach/website"
command = """
    # Create necessary directories (in case they don't exist)
    mkdir -p outreach/website/documents outreach/website/download
    
    # Run the build-cs108 task to build JAR and copy to website directory
    ./gradlew build-cs108 --stacktrace --info || echo "Gradle build failed, proceeding with fallback"
    
    # Check if JAR was built and copied successfully
    if [ -f "outreach/website/download/SettlersOfAsgard.jar" ]; then
        echo "JAR file successfully copied to website download directory"
    else
        echo "JAR file not found in website directory, creating fallback placeholder"
        echo "This is a placeholder JAR. Please visit our GitHub repository for the full game." > outreach/website/download/SettlersOfAsgard.jar
        
        # Ensure we have docs even if build-cs108 failed
        cp -f docs/Spielbeschreibungen/*.pdf outreach/website/documents/ || echo "Warning: PDF files not copied"
    fi
    
    # Verify that the website files exist
    ls -la outreach/website/
    ls -la outreach/website/download/
    ls -la outreach/website/documents/
"""

[build.environment]
  # Set Java version to 17
  JAVA_VERSION = "17"
  NODE_VERSION = "16"
  # Set Gradle options
  GRADLE_OPTS = "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true"

# This redirect ensures any path will serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/download/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
