[build]
publish = "outreach/website"
command = """
    # Create necessary directories
    mkdir -p outreach/website/documents outreach/website/download
    
    # Copy documentation
    cp -f docs/Spielbeschreibungen/*.pdf outreach/website/documents/ || echo "Warning: PDF files not copied"
    
    # Skip the JAR build - it requires Java 17 and JavaFX
    echo "Skipping JAR build for website deployment"
    
    # Create a placeholder JAR file if needed
    touch outreach/website/download/SettlersOfAsgard.jar
    
    # Verify that the website files exist
    ls -la outreach/website/
"""

[build.environment]
  # Set Java version to 17
  JAVA_VERSION = "17"
  NODE_VERSION = "16"

# This redirect is critical - it ensures any path will serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/download/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
