package ch.unibas.dmi.dbis.cs108.shared.entities.Purchasables;

import ch.unibas.dmi.dbis.cs108.shared.entities.GameEntity;
import ch.unibas.dmi.dbis.cs108.shared.entities.Purchasables.Statues.Statue;
import com.google.gson.JsonObject;

/**
 * Base class for entities that can be purchased by players.
 * Extends the GameEntity class with price information.
 */
public abstract class PurchasableEntity extends GameEntity {
    /**
     * The cost to purchase this entity.
     */
    protected int price;

    /**
     * The resource value of this entity.
     */
    protected int resourceValue;

    /**
     * Default constructor for PurchasableEntity.
     */
    public PurchasableEntity() {}

    /**
     * Constructs a new PurchasableEntity with specified values.
     *
     * @param id The unique identifier for this entity
     * @param name The name of this entity
     * @param description The description of this entity
     * @param price The purchase price of this entity
     */
    public PurchasableEntity(int id, String name, String description, int price, int resourceValue) {
        super(id, name, description);
        this.price = price;
        this.resourceValue = resourceValue;
    }

    /**
     * Returns the purchase price of this entity.
     *
     * @return The price of this entity
     */
    public int getPrice() { return price; }

    /**
     * Returns if this entity is a structure.
     */
    public boolean isStructure() { return this instanceof Structure; }

    /**
     * Returns if this entity is a statue.
     */
    public boolean isStatue() { return this instanceof Statue; }

    /**
     * Returns the resource value of this entity.
     * This value is used to determine the amount of resources generated by this entity per turn.
     * This can either be energy (for structures) or runes (for statues).
     *
     * @return The resource value of this entity
     */
    public int getResourceValue() { return resourceValue; }

    /**
     * Loads entity data from a JSON object.
     * Extends the parent method to also load price data.
     *
     * @param json The JSON object containing entity data
     */
    @Override
    protected void loadFromJson(JsonObject json) {
        super.loadFromJson(json);
        this.price = json.get("price").getAsInt();
        this.resourceValue = json.get("resourceValue").getAsInt();
    }
}